-- Datos INVENTADOS para ver el CRM lleno (7-oct-2026). Solo para la base de
-- pruebas (rhf-leads-preview) y el arnés de Node; nunca para producción.
-- Personas de mentira con «(demo)» en el nombre, correos @example.com y
-- teléfonos +57300555xxxx. Las fechas van relativas a hoy.
-- Se puede correr dos veces: no repite lo que ya existe.

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-34 days', '-3 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-34 days', '-3 hours'), 'Camila Rojas (demo)', '+573005550101', 'camila.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', '/proyectos/doral-west', 'meta_ads', 'meta_ads', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-34 days', '-3 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'camila.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-34 days', '-3 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days'), 'compra', 'propuesta', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days'), NULL, 'A', 'doral-west', 'vivir', 0, 'meta_ads', '600_900', 'credito', 690000000, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-34 days', '-3 hours'), '+4 minutes'), 4, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-33 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-26 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days'), NULL, 'Llamar para cerrar la propuesta', date('now', '-5 hours', '+1 day')
  FROM crm_contactos c WHERE c.correo = 'camila.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-34 days', '-3 hours'), 'formulario', 'Dato de demostración. Llegó por meta_ads, campaña doral-west-oct.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'camila.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-20 days', '-5 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-20 days', '-5 hours'), 'Andrés Pardo (demo)', '+573005550102', 'andres.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', '/proyectos/doral-country', 'meta_ads', 'meta_ads', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-20 days', '-5 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'andres.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-20 days', '-5 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days'), 'compra', 'recorrido_hecho', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days'), NULL, 'A', 'doral-country', 'renta_corta', 0, 'meta_ads', '400_600', 'mixto', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-20 days', '-5 hours'), '+7 minutes'), 7, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-19 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days'), NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'andres.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
UPDATE crm_oportunidades SET higiene_nivel = 7, higiene_en = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE contacto_id = (SELECT id FROM crm_contactos WHERE correo = 'andres.demo@example.com') AND higiene_nivel = 0;
INSERT INTO crm_tareas (contacto_id, oportunidad_id, creado_en, titulo, vence_en, origen, regla) SELECT o.contacto_id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'Retomar: 7 días sin actividad', date('now', '-5 hours'), 'sistema', 'higiene_7' FROM crm_oportunidades o JOIN crm_contactos c ON c.id = o.contacto_id WHERE c.correo = 'andres.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_tareas t WHERE t.oportunidad_id = o.id AND t.regla LIKE 'higiene_%');
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-20 days', '-5 hours'), 'formulario', 'Dato de demostración. Llegó por meta_ads, campaña doral-country-renta.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'andres.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-47 days', '-2 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-47 days', '-2 hours'), 'Valentina Gómez (demo)', '+573005550103', 'valentina.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', '/proyectos/doral-suite', 'google_ads', 'google_ads', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-47 days', '-2 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-22 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'valentina.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-47 days', '-2 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-22 days'), 'compra', 'separo', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-22 days'), NULL, 'A', 'doral-suite', 'patrimonio', 1, 'google_ads', '250_400', 'propios', 340000000, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-47 days', '-2 hours'), '+3 minutes'), 3, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-22 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-47 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-40 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-30 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-22 days'), NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'valentina.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-47 days', '-2 hours'), 'formulario', 'Dato de demostración. Llegó por google_ads, campaña busqueda-cartagena.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'valentina.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days', '-4 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days', '-4 hours'), 'Julián Mora (demo)', '+573005550104', 'julian.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', '/proyectos/blue-garden', 'youtube_ads', 'youtube_ads', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days', '-4 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'julian.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days', '-4 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days'), 'compra', 'calificado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days'), NULL, 'B', 'blue-garden', 'vivir', 0, 'youtube_ads', '250_400', 'credito', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days', '-4 hours'), '+12 minutes'), 12, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days'), NULL, NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'julian.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
UPDATE crm_oportunidades SET higiene_nivel = 7, higiene_en = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE contacto_id = (SELECT id FROM crm_contactos WHERE correo = 'julian.demo@example.com') AND higiene_nivel = 0;
INSERT INTO crm_tareas (contacto_id, oportunidad_id, creado_en, titulo, vence_en, origen, regla) SELECT o.contacto_id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'Retomar: 7 días sin actividad', date('now', '-5 hours'), 'sistema', 'higiene_7' FROM crm_oportunidades o JOIN crm_contactos c ON c.id = o.contacto_id WHERE c.correo = 'julian.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_tareas t WHERE t.oportunidad_id = o.id AND t.regla LIKE 'higiene_%');
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days', '-4 hours'), 'formulario', 'Dato de demostración. Llegó por youtube_ads, campaña youtube-recorrido-norte.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'julian.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days', '-6 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days', '-6 hours'), 'Sara Medina (demo)', '+573005550105', 'sara.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', '/proyectos/doral-west', 'meta_ads', 'meta_ads', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days', '-6 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'sara.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days', '-6 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days'), 'compra', 'contactado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days'), NULL, 'sin', 'doral-west', 'vivir', 0, 'meta_ads', 'no_se', 'no_se', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days', '-6 hours'), '+25 minutes'), 25, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days'), NULL, NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'sara.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days', '-6 hours'), 'formulario', 'Dato de demostración. Llegó por meta_ads, campaña doral-west-oct.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'sara.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days', '-1 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days', '-1 hours'), 'Felipe Castro (demo)', '+573005550106', 'felipe.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', '/proyectos/doral-country', 'google_ads', 'google_ads', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days', '-1 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'felipe.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days', '-1 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days'), 'compra', 'recorrido_agendado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days'), NULL, 'B', 'doral-country', 'renta_tradicional', 0, 'google_ads', '400_600', 'credito', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days', '-1 hours'), '+48 minutes'), 48, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days'), NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'felipe.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days', '-1 hours'), 'formulario', 'Dato de demostración. Llegó por google_ads, campaña busqueda-cartagena.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'felipe.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), 'Laura Pineda (demo)', '+573005550107', 'laura.demo@example.com', 'Cartagena', 'es', 'whatsapp', 'whatsapp', NULL, 'whatsapp_ia', 'whatsapp_ia', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'laura.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days'), 'compra', 'contactado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days'), NULL, 'sin', 'doral-suite', 'renta_corta', 0, 'whatsapp_ia', '250_400', 'propios', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), '+130 minutes'), 130, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days'), NULL, NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'laura.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), 'formulario', 'Dato de demostración. Llegó por whatsapp_ia.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'laura.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-41 days', '-8 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-41 days', '-8 hours'), 'Mateo Ruiz (demo)', '+573005550108', 'mateo.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', '/proyectos/doral-west', 'meta_ads', 'meta_ads', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-41 days', '-8 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-40 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'mateo.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-41 days', '-8 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-33 days'), 'compra', 'nutrir', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-33 days'), NULL, 'C', 'doral-west', 'vivir', 0, 'meta_ads', '600_900', 'venta_otro', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-41 days', '-8 hours'), '+300 minutes'), 300, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-33 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-40 days'), NULL, NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'mateo.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-41 days', '-8 hours'), 'formulario', 'Dato de demostración. Llegó por meta_ads, campaña doral-west-sep.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'mateo.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-26 days', '-3 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-26 days', '-3 hours'), 'Daniela Ortiz (demo)', '+573005550109', 'daniela.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', NULL, 'redes', 'redes', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-26 days', '-3 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-25 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'daniela.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-26 days', '-3 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days'), 'compra', 'perdido', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days'), 'No responde', 'C', 'blue-garden', 'vivir', 1, 'redes', 'hasta_250', 'credito', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-26 days', '-3 hours'), '+9 minutes'), 9, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-25 days'), NULL, NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'daniela.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-26 days', '-3 hours'), 'formulario', 'Dato de demostración. Llegó por redes.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'daniela.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-16 days', '-7 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-16 days', '-7 hours'), 'Sebastián León (demo)', '+573005550110', 'sebastian.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', '/proyectos/doral-west', 'youtube_ads', 'youtube_ads', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-16 days', '-7 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'sebastian.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-16 days', '-7 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days'), 'compra', 'propuesta', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days'), NULL, 'A', 'doral-west', 'patrimonio', 0, 'youtube_ads', 'mas_900', 'propios', 880000000, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-16 days', '-7 hours'), '+6 minutes'), 6, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-16 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-11 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days'), NULL, 'Llamar para cerrar la propuesta', date('now', '-5 hours', '+1 day')
  FROM crm_contactos c WHERE c.correo = 'sebastian.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-16 days', '-7 hours'), 'formulario', 'Dato de demostración. Llegó por youtube_ads, campaña youtube-doral-west.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'sebastian.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 minutes'), 'Natalia Vargas (demo)', '+573005550111', 'natalia.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', '/proyectos/doral-country', 'meta_ads', 'meta_ads', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 minutes'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', NULL
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'natalia.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 minutes'), 'compra', 'nuevo', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 minutes'), NULL, 'sin', 'doral-country', 'renta_corta', 0, 'meta_ads', '400_600', 'credito', NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 minutes'), NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 minutes'), NULL, NULL, NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'natalia.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 minutes'), 'formulario', 'Dato de demostración. Llegó por meta_ads, campaña doral-country-renta.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'natalia.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 minutes'), 'Tomás Herrera (demo)', '+573005550112', 'tomas.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', '/proyectos/doral-suite', 'google_ads', 'google_ads', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 minutes'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', NULL
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'tomas.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 minutes'), 'compra', 'nuevo', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 minutes'), NULL, 'sin', 'doral-suite', 'patrimonio', 0, 'google_ads', '250_400', 'no_se', NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 minutes'), NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 minutes'), NULL, NULL, NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'tomas.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 minutes'), 'formulario', 'Dato de demostración. Llegó por google_ads, campaña busqueda-cartagena.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'tomas.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days', '-1 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days', '-1 hours'), 'Isabella Cruz (demo)', '+573005550113', 'isabella.demo@example.com', 'Cartagena', 'es', 'chat', 'chat', NULL, 'chat_ia', 'chat_ia', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days', '-1 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'isabella.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days', '-1 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days'), 'compra', 'calificado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days'), NULL, 'B', 'blue-garden', 'vivir', 0, 'chat_ia', '250_400', 'mixto', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days', '-1 hours'), '+18 minutes'), 18, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days'), NULL, NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'isabella.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days', '-1 hours'), 'formulario', 'Dato de demostración. Llegó por chat_ia.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'isabella.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days', '-2 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days', '-2 hours'), 'Martín Salazar (demo)', '+573005550114', 'martin.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', NULL, 'directo', 'directo', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days', '-2 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'martin.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days', '-2 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days'), 'compra', 'contactado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days'), NULL, 'sin', NULL, NULL, 0, 'directo', NULL, NULL, NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days', '-2 hours'), '+35 minutes'), 35, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days'), NULL, NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'martin.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
UPDATE crm_oportunidades SET higiene_nivel = 15, higiene_en = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE contacto_id = (SELECT id FROM crm_contactos WHERE correo = 'martin.demo@example.com') AND higiene_nivel = 0;
INSERT INTO crm_tareas (contacto_id, oportunidad_id, creado_en, titulo, vence_en, origen, regla) SELECT o.contacto_id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'En riesgo: 15 días sin actividad. Llámalo o pásalo a Nutrir', date('now', '-5 hours'), 'sistema', 'higiene_15' FROM crm_oportunidades o JOIN crm_contactos c ON c.id = o.contacto_id WHERE c.correo = 'martin.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_tareas t WHERE t.oportunidad_id = o.id AND t.regla LIKE 'higiene_%');
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days', '-2 hours'), 'formulario', 'Dato de demostración. Llegó por directo.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'martin.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 days', '-4 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 days', '-4 hours'), 'Paula Reyes (demo)', '+573005550115', 'paula.demo@example.com', 'Cartagena', 'es', 'referido', 'referido', NULL, 'referido', 'referido', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 days', '-4 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'paula.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 days', '-4 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days'), 'compra', 'recorrido_agendado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days'), NULL, 'A', 'doral-west', 'vivir', 0, 'referido', '600_900', 'credito', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 days', '-4 hours'), '+2 minutes'), 2, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days'), NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'paula.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 days', '-4 hours'), 'formulario', 'Dato de demostración. Llegó por referido.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'paula.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-23 days', '-6 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-23 days', '-6 hours'), 'Ricardo Peña (demo)', '+573005550116', 'ricardo.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', '/proyectos/doral-country', 'meta_ads', 'meta_ads', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-23 days', '-6 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-23 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'ricardo.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-23 days', '-6 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-23 days'), 'compra', 'contactado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-23 days'), NULL, 'B', 'doral-country', 'renta_corta', 0, 'meta_ads', '400_600', 'credito', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-23 days', '-6 hours'), '+11 minutes'), 11, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-23 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-23 days'), NULL, NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'ricardo.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
UPDATE crm_oportunidades SET higiene_nivel = 15, higiene_en = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE contacto_id = (SELECT id FROM crm_contactos WHERE correo = 'ricardo.demo@example.com') AND higiene_nivel = 0;
INSERT INTO crm_tareas (contacto_id, oportunidad_id, creado_en, titulo, vence_en, origen, regla) SELECT o.contacto_id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'En riesgo: 15 días sin actividad. Llámalo o pásalo a Nutrir', date('now', '-5 hours'), 'sistema', 'higiene_15' FROM crm_oportunidades o JOIN crm_contactos c ON c.id = o.contacto_id WHERE c.correo = 'ricardo.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_tareas t WHERE t.oportunidad_id = o.id AND t.regla LIKE 'higiene_%');
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-23 days', '-6 hours'), 'formulario', 'Dato de demostración. Llegó por meta_ads, campaña doral-country-renta.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'ricardo.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days', '-3 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days', '-3 hours'), 'Gloria Suárez (demo)', '+573005550117', 'gloria.demo@example.com', 'Cartagena', 'es', 'formulario', 'formulario', NULL, 'buscadores', 'buscadores', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days', '-3 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'gloria.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days', '-3 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days'), 'venta', 'consignado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days'), NULL, 'sin', NULL, NULL, 0, 'buscadores', NULL, NULL, 520000000, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days', '-3 hours'), '+20 minutes'), 20, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days'), NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'gloria.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days', '-3 hours'), 'formulario', 'Dato de demostración. Llegó por buscadores.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'gloria.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_contactos (creado_en, actualizado_en, nombre, telefono, correo, ciudad, idioma, fuente, fuente_ultima, pagina_entrada, canal, canal_ultimo, autorizacion_fecha, autorizacion_version, autorizacion_canal, autorizacion_evidencia, ultimo_contacto_en)
  SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days', '-2 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days', '-2 hours'), 'Hernán Díaz (demo)', '+573005550118', 'hernan.demo@example.com', 'Cartagena', 'es', 'whatsapp', 'whatsapp', NULL, 'whatsapp_ia', 'whatsapp_ia', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days', '-2 hours'), 'demo', 'otro', 'Dato de demostración, inventado (no es una persona real)', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days')
  WHERE NOT EXISTS (SELECT 1 FROM crm_contactos WHERE correo = 'hernan.demo@example.com');
INSERT INTO crm_oportunidades (contacto_id, creado_en, actualizado_en, tipo, etapa, etapa_desde, motivo_perdida, puntaje, interes, proposito, cerrada, canal, rango_presupuesto, pago, valor_estimado, espera_desde, primer_intento_en, minutos_respuesta, ultima_actividad_en, fase_contactado_en, fase_presentacion_en, fase_cotizacion_en, fase_cierre_en, proxima_accion, proxima_accion_en)
  SELECT id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days', '-2 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days'), 'venta', 'contactado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days'), NULL, 'sin', NULL, NULL, 0, 'whatsapp_ia', NULL, NULL, NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days', '-2 hours'), '+45 minutes'), 45, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days'), NULL, NULL, NULL, NULL, NULL
  FROM crm_contactos c WHERE c.correo = 'hernan.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_oportunidades o WHERE o.contacto_id = c.id);
INSERT INTO crm_actividades (contacto_id, oportunidad_id, creado_en, tipo, texto, autor)
  SELECT c.id, o.id, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days', '-2 hours'), 'formulario', 'Dato de demostración. Llegó por whatsapp_ia.', 'sitio' FROM crm_contactos c JOIN crm_oportunidades o ON o.contacto_id = c.id
  WHERE c.correo = 'hernan.demo@example.com' AND NOT EXISTS (SELECT 1 FROM crm_actividades a WHERE a.contacto_id = c.id);

INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-7 days'), 'meta_ads', 1450000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-7 days') AND canal = 'meta_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-7 days'), 'google_ads', 820000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-7 days') AND canal = 'google_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-7 days'), 'youtube_ads', 400000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-7 days') AND canal = 'youtube_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-14 days'), 'meta_ads', 1300000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-14 days') AND canal = 'meta_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-14 days'), 'google_ads', 760000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-14 days') AND canal = 'google_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-14 days'), 'youtube_ads', 400000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-14 days') AND canal = 'youtube_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-21 days'), 'meta_ads', 1600000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-21 days') AND canal = 'meta_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-21 days'), 'google_ads', 900000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-21 days') AND canal = 'google_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-21 days'), 'youtube_ads', 350000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-21 days') AND canal = 'youtube_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-28 days'), 'meta_ads', 1200000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-28 days') AND canal = 'meta_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-28 days'), 'google_ads', 650000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-28 days') AND canal = 'google_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-28 days'), 'youtube_ads', 0, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-28 days') AND canal = 'youtube_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-35 days'), 'meta_ads', 1100000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-35 days') AND canal = 'meta_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-35 days'), 'google_ads', 600000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-35 days') AND canal = 'google_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-35 days'), 'youtube_ads', 0, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-35 days') AND canal = 'youtube_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-42 days'), 'meta_ads', 900000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-42 days') AND canal = 'meta_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-42 days'), 'google_ads', 500000, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-42 days') AND canal = 'google_ads');
INSERT INTO crm_inversion (semana, canal, monto, nota, creado_en, actualizado_en, autor) SELECT date('now', '-5 hours', 'weekday 1', '-42 days'), 'youtube_ads', 0, 'Monto de demostración, inventado', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'demo' WHERE NOT EXISTS (SELECT 1 FROM crm_inversion WHERE semana = date('now', '-5 hours', 'weekday 1', '-42 days') AND canal = 'youtube_ads');

INSERT INTO agente_conversaciones (sesion, canal, usuario, telefono, contacto_id, iniciada_en, ultimo_en, mensajes, primer_mensaje, creado_en, actualizado_en)
  SELECT 'demo-wa-laura', 'whatsapp', '573005550107', '+573005550107', (SELECT id FROM crm_contactos WHERE telefono = '+573005550107'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), '+12 minutes'), 6, 'Hola, buenas tardes. Vi que tienen apartamentos en Doral Suite, ¿todavía hay disponibles?', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE NOT EXISTS (SELECT 1 FROM agente_conversaciones WHERE sesion = 'demo-wa-laura');
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-wa-laura-0', 'persona', 'Hola, buenas tardes. Vi que tienen apartamentos en Doral Suite, ¿todavía hay disponibles?', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), '+0 minutes') FROM agente_conversaciones WHERE sesion = 'demo-wa-laura';
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-wa-laura-1', 'agente', '¡Hola! Sí, en Doral Suite hay unidades de entrega inmediata. Los precios van desde $295.000.000, con corte de septiembre de 2026. ¿Lo buscas para vivir o para invertir?', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), '+2 minutes') FROM agente_conversaciones WHERE sesion = 'demo-wa-laura';
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-wa-laura-2', 'persona', 'Para renta corta, tipo Airbnb. ¿Se puede?', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), '+4 minutes') FROM agente_conversaciones WHERE sesion = 'demo-wa-laura';
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-wa-laura-3', 'agente', 'Te cuento lo que sabemos y lo que hay que confirmar: la renta corta depende del reglamento del conjunto. Rafael te puede mostrar el documento en una llamada. ¿Quieres que te llame?', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), '+6 minutes') FROM agente_conversaciones WHERE sesion = 'demo-wa-laura';
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-wa-laura-4', 'persona', 'Sí, mañana a las 10 a. m.', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), '+8 minutes') FROM agente_conversaciones WHERE sesion = 'demo-wa-laura';
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-wa-laura-5', 'agente', 'Listo. Usamos tu nombre y tu número solo para agendar esa llamada: rhfliving.com/privacidad. Rafael te llama mañana a las 10 a. m.', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days', '-2 hours'), '+10 minutes') FROM agente_conversaciones WHERE sesion = 'demo-wa-laura';

INSERT INTO agente_conversaciones (sesion, canal, usuario, telefono, contacto_id, iniciada_en, ultimo_en, mensajes, primer_mensaje, creado_en, actualizado_en)
  SELECT 'demo-web-isabella', 'webchat', NULL, NULL, (SELECT id FROM crm_contactos WHERE correo = 'isabella.demo@example.com'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days', '-1 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days', '-1 hours'), '+8 minutes'), 4, 'Hola, ¿cuánto cuesta un apartamento en Blue Garden?', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE NOT EXISTS (SELECT 1 FROM agente_conversaciones WHERE sesion = 'demo-web-isabella');
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-web-isabella-0', 'persona', 'Hola, ¿cuánto cuesta un apartamento en Blue Garden?', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days', '-1 hours'), '+0 minutes') FROM agente_conversaciones WHERE sesion = 'demo-web-isabella';
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-web-isabella-1', 'agente', '¡Hola! En Blue Garden los apartamentos van desde $229.000.000 hasta $376.640.000, con corte de septiembre de 2026. ¿Cuántas alcobas necesitas?', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days', '-1 hours'), '+2 minutes') FROM agente_conversaciones WHERE sesion = 'demo-web-isabella';
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-web-isabella-2', 'persona', 'Dos alcobas. Pagaría una parte con crédito.', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days', '-1 hours'), '+4 minutes') FROM agente_conversaciones WHERE sesion = 'demo-web-isabella';
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-web-isabella-3', 'agente', 'Perfecto. Con crédito y una parte de cuota inicial hay buenas opciones. ¿Te gustaría que Rafael te llame para explicarte el plan de pagos? Necesito el número de WhatsApp al que te llama.', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days', '-1 hours'), '+6 minutes') FROM agente_conversaciones WHERE sesion = 'demo-web-isabella';

INSERT INTO agente_conversaciones (sesion, canal, usuario, telefono, contacto_id, iniciada_en, ultimo_en, mensajes, primer_mensaje, creado_en, actualizado_en)
  SELECT 'demo-wa-sin-ficha', 'whatsapp', '573005550190', '+573005550190', (SELECT id FROM crm_contactos WHERE telefono = '+573005550190'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days', '-3 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days', '-3 hours'), '+8 minutes'), 4, 'Buenas, ¿ustedes venden lotes en Turbaco?', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE NOT EXISTS (SELECT 1 FROM agente_conversaciones WHERE sesion = 'demo-wa-sin-ficha');
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-wa-sin-ficha-0', 'persona', 'Buenas, ¿ustedes venden lotes en Turbaco?', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days', '-3 hours'), '+0 minutes') FROM agente_conversaciones WHERE sesion = 'demo-wa-sin-ficha';
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-wa-sin-ficha-1', 'agente', '¡Hola! Por ahora no tenemos lotes en Turbaco en la cartera. En Turbaco está Blue Garden, un condominio de apartamentos. ¿Te cuento de él?', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days', '-3 hours'), '+2 minutes') FROM agente_conversaciones WHERE sesion = 'demo-wa-sin-ficha';
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-wa-sin-ficha-2', 'persona', 'No, gracias, busco lote.', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days', '-3 hours'), '+4 minutes') FROM agente_conversaciones WHERE sesion = 'demo-wa-sin-ficha';
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-wa-sin-ficha-3', 'agente', 'Entendido. Si más adelante te interesa un apartamento o una casa en la Zona Norte de Cartagena, aquí estamos.', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days', '-3 hours'), '+6 minutes') FROM agente_conversaciones WHERE sesion = 'demo-wa-sin-ficha';

INSERT INTO agente_conversaciones (sesion, canal, usuario, telefono, contacto_id, iniciada_en, ultimo_en, mensajes, primer_mensaje, creado_en, actualizado_en)
  SELECT 'demo-web-visitante', 'webchat', NULL, NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 hours'), '+4 minutes'), 2, '¿Qué documentos necesito para separar?', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE NOT EXISTS (SELECT 1 FROM agente_conversaciones WHERE sesion = 'demo-web-visitante');
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-web-visitante-0', 'persona', '¿Qué documentos necesito para separar?', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 hours'), '+0 minutes') FROM agente_conversaciones WHERE sesion = 'demo-web-visitante';
INSERT OR IGNORE INTO agente_mensajes (conversacion_id, origen_id, rol, texto, en) SELECT id, 'demo-web-visitante-1', 'agente', 'Para separar se firma un acuerdo con el promotor y se paga la separación. Los documentos exactos los confirma Rafael según el proyecto. ¿Te interesa alguno en particular?', strftime('%Y-%m-%dT%H:%M:%fZ', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 hours'), '+2 minutes') FROM agente_conversaciones WHERE sesion = 'demo-web-visitante';

INSERT INTO agente_sincronizacion (fuente, ultimo_en, lotes, mensajes) SELECT 'atencion', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 1, (SELECT COUNT(*) FROM agente_mensajes) WHERE NOT EXISTS (SELECT 1 FROM agente_sincronizacion WHERE fuente = 'atencion');
